[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.processing]
  skip_processing = false

[build.processing.headers]
  transform = "headers"